[build]
  publish = "dist"
  command = "npx npm-run-all build:css build:html"

[[redirects]]
  from = "/api/*"
  to = "https://duncandavidson-api.azurewebsites.net/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/rss*"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/index.rss"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/index.xml"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/xml/rss.xml"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/atom*"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/blog/atom*"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/blog/feed*"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/blog/index.rss"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/blog/index.xml"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/blog/rss*"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/blog/xml"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/index.rdf"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/feed"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/feed/*"
  to = "https://duncandavidson.com/feed.xml"
  status = 301
  force = true

